module.exports = [
  {
    id: 46841,
    domain: null,
    url: 'https://GradeUp.com/launch',
    consumer_key: 'gradeup_key',
    name: 'GradeUp',
    description: 'GradeUp is a great tool',
    created_at: '2019-06-19T16:25:28Z',
    updated_at: '2019-06-19T16:25:28Z',
    privacy_level: 'public',
    custom_fields: {},
    workflow_state: 'public',
    vendor_help_link: null,
    account_navigation: null,
    similarity_detection: null,
    assignment_edit: null,
    assignment_menu: null,
    assignment_selection: null,
    assignment_view: null,
    collaboration: null,
    course_assignments_menu: null,
    course_home_sub_navigation: null,
    course_navigation: {
      url: 'https://GradeUp.com/launch',
      text: 'GradeUp',
      visibility: 'public',
      default: 'enabled',
      enabled: 'true',
      label: 'GradeUp',
      selection_width: 800,
      selection_height: 400,
      icon_url: '',
    },
    course_settings_sub_navigation: null,
    discussion_topic_menu: null,
    editor_button: null,
    file_menu: null,
    global_navigation: null,
    homework_submission: null,
    link_selection: null,
    migration_selection: null,
    module_menu: null,
    post_grades: null,
    quiz_menu: null,
    resource_selection: null,
    tool_configuration: null,
    user_navigation: null,
    wiki_page_menu: null,
    icon_url: '',
    not_selectable: false,
    version: '1.1',
  },
  {
    id: 46842,
    domain: null,
    url: 'https://SwipeIn.com/launch',
    consumer_key: 'swipein_key',
    name: 'SwipeIn',
    description: 'SwipeIn is a great tool',
    created_at: '2019-06-19T16:31:44Z',
    updated_at: '2019-06-19T16:31:44Z',
    privacy_level: 'anonymous',
    custom_fields: {},
    workflow_state: 'anonymous',
    vendor_help_link: null,
    account_navigation: null,
    similarity_detection: null,
    assignment_edit: null,
    assignment_menu: null,
    assignment_selection: null,
    assignment_view: null,
    collaboration: null,
    course_assignments_menu: null,
    course_home_sub_navigation: null,
    course_navigation: {
      url: 'https://SwipeIn.com/launch',
      text: 'SwipeIn',
      visibility: 'public',
      default: 'enabled',
      enabled: 'true',
      label: 'SwipeIn',
      selection_width: 800,
      selection_height: 400,
      icon_url: '',
    },
    course_settings_sub_navigation: null,
    discussion_topic_menu: null,
    editor_button: null,
    file_menu: null,
    global_navigation: null,
    homework_submission: null,
    link_selection: null,
    migration_selection: null,
    module_menu: null,
    post_grades: null,
    quiz_menu: null,
    resource_selection: null,
    tool_configuration: null,
    user_navigation: null,
    wiki_page_menu: null,
    icon_url: '',
    not_selectable: false,
    version: '1.1',
  },
];
